import random
structure_romans = [
    {
        "nom": "Romance historique épistolaire",
        "genres": ["Roman sentimental", "Roman historique"],
        "ton": "Lyrique",
        "public": "Adulte",
        "format": "Roman épistolaire",
        "structure": "Cadre",
        "cadre": {"lieu": "Campagne historique", "temps": "Passé"},
        "nombre_chapitres": 12,
        "caracteres_par_chapitre": 6250,
        "schema_principal": "SchemaNarratifCadre",
        "schema_complementaire": "SchemaNarratifClassique",
    },
    {
        "nom": "Thriller psychologique contemporain",
        "genres": ["Roman policier", "Roman psychologique"],
        "ton": "Sombre",
        "public": "Adulte",
        "format": "Roman choral",
        "structure": "Fragmentée",
        "cadre": {"lieu": "Ville contemporaine", "temps": "Présent"},
        "nombre_chapitres": 15,
        "caracteres_par_chapitre": 5000,
        "schema_principal": "SchemaNarratifFragmenté",
        "schema_complementaire": "SchemaNarratifFreytag",
    },
    {
        "nom": "Science-fantasy épique",
        "genres": ["Roman de fantasy", "Roman de science-fiction"],
        "ton": "Épique",
        "public": "Jeune adulte (YA)",
        "format": "Roman classique",
        "structure": "Linéaire",
        "cadre": {"lieu": "Univers inventé", "temps": "Intemporel"},
        "nombre_chapitres": 10,
        "caracteres_par_chapitre": 7500,
        "schema_principal": "VoyageDuHeros",
        "schema_complementaire": "SchemaActanciel",
    },
    {
        "nom": "Uchronie philosophique",
        "genres": ["Roman historique", "Roman de science-fiction"],
        "ton": "Ironique",
        "public": "Adulte",
        "format": "Roman mosaïque",
        "structure": "In medias res",
        "cadre": {"lieu": "Ville contemporaine", "temps": "Futur"},
        "nombre_chapitres": 14,
        "caracteres_par_chapitre": 5357,
        "schema_principal": "SchemaNarratifInMediasRes",
        "schema_complementaire": "SchemaQuinaire",
    },
    {
        "nom": "Romantasy lyrique pour jeunes adultes",
        "genres": ["Roman sentimental", "Roman de fantasy"],
        "ton": "Lyrique",
        "public": "Jeune adulte (YA)",
        "format": "Roman journal",
        "structure": "Flashback",
        "cadre": {"lieu": "Univers inventé", "temps": "Intemporel"},
        "nombre_chapitres": 15,
        "caracteres_par_chapitre": 5000,
        "schema_principal": "SchemaNarratifFlashback",
        "schema_complementaire": "SchemaActanciel",
    },
    {
        "nom": "Chick lit humoristique",
        "genres": ["Roman humoristique", "Roman sentimental"],
        "ton": "Comique",
        "public": "Adulte",
        "format": "Roman classique",
        "structure": "Linéaire",
        "cadre": {"lieu": "Ville contemporaine", "temps": "Présent"},
        "nombre_chapitres": 12,
        "caracteres_par_chapitre": 6250,
        "schema_principal": "SchemaNarratifClassique",
        "schema_complementaire": "SchemaNarratifStructure3Actes",
    },
    {
        "nom": "Dystopie sociale post-apocalyptique",
        "genres": ["Roman dystopique", "Roman social"],
        "ton": "Tragique",
        "public": "Jeune adulte (YA)",
        "format": "Roman graphique",
        "structure": "Circulaire",
        "cadre": {"lieu": "Société post-apocalyptique", "temps": "Après une catastrophe"},
        "nombre_chapitres": 16,
        "caracteres_par_chapitre": 4688,
        "schema_principal": "SchemaNarratifCirculaire",
        "schema_complementaire": "SchemaNarratifFreytag",
    },
    {
        "nom": "Fantastique gothique en huis clos",
        "genres": ["Roman fantastique", "Roman d'horreur"],
        "ton": "Sombre",
        "public": "Adulte",
        "format": "Roman classique",
        "structure": "Cadre",
        "cadre": {"lieu": "Lieu clos (huis clos)", "temps": "Passé"},
        "nombre_chapitres": 8,
        "caracteres_par_chapitre": 9375,
        "schema_principal": "SchemaNarratifCadre",
        "schema_complementaire": "SchemaNarratifHorreur",
    },
    {
        "nom": "Cyberpunk dramatique",
        "genres": ["Roman de science-fiction"],
        "ton": "Dramatique",
        "public": "Adulte",
        "format": "Roman choral",
        "structure": "Fragmentée",
        "cadre": {"lieu": "Futur urbain", "temps": "Futur"},
        "nombre_chapitres": 20,
        "caracteres_par_chapitre": 3750,
        "schema_principal": "SchemaNarratifFragmenté",
        "schema_complementaire": "SchemaQuinaire",
    },
    {
        "nom": "Roman initiatique pour enfants",
        "genres": ["Roman initiatique"],
        "ton": "Comique",
        "public": "Enfant",
        "format": "Roman classique",
        "structure": "Linéaire",
        "cadre": {"lieu": "Ville contemporaine", "temps": "Présent"},
        "nombre_chapitres": 10,
        "caracteres_par_chapitre": 7500,
        "schema_principal": "VoyageDuHeros",
        "schema_complementaire": "SchemaNarratifClassique",
    },
    {
        "nom": "Steampunk à suspense",
        "genres": ["Roman historique", "Roman de science-fiction"],
        "ton": "Dramatique",
        "public": "Adulte",
        "format": "Roman mosaïque",
        "structure": "In medias res",
        "cadre": {"lieu": "Ville industrielle", "temps": "Passé"},
        "nombre_chapitres": 13,
        "caracteres_par_chapitre": 5769,
        "schema_principal": "SchemaNarratifInMediasRes",
        "schema_complementaire": "SchemaActanciel",
    },
    {
        "nom": "Roman philosophique spatial",
        "genres": ["Roman philosophique", "Roman de science-fiction"],
        "ton": "Lyrique",
        "public": "Adulte",
        "format": "Roman journal",
        "structure": "Fragmentée",
        "cadre": {"lieu": "Espace intergalactique", "temps": "Futur lointain"},
        "nombre_chapitres": 18,
        "caracteres_par_chapitre": 4167,
        "schema_principal": "SchemaNarratifFragmenté",
        "schema_complementaire": "SchemaNarratifCirculaire",
    },
    {
        "nom": "Roman noir social",
        "genres": ["Roman noir", "Roman social"],
        "ton": "Sombre",
        "public": "Adulte",
        "format": "Roman choral",
        "structure": "Flashback",
        "cadre": {"lieu": "Ville contemporaine", "temps": "Présent"},
        "nombre_chapitres": 15,
        "caracteres_par_chapitre": 5000,
        "schema_principal": "SchemaNarratifFlashback",
        "schema_complementaire": "SchemaDramatique",
    },
    {
        "nom": "Épopée fantasy initiatique",
        "genres": ["Roman de fantasy", "Roman initiatique"],
        "ton": "Épique",
        "public": "Jeune adulte (YA)",
        "format": "Roman classique",
        "structure": "Linéaire",
        "cadre": {"lieu": "Univers inventé", "temps": "Intemporel"},
        "nombre_chapitres": 12,
        "caracteres_par_chapitre": 6250,
        "schema_principal": "VoyageDuHeros",
        "schema_complementaire": "SchemaActanciel",
    },
    {
        "nom": "Autofiction existentielle",
        "genres": ["Roman autobiographique", "Roman philosophique"],
        "ton": "Lyrique",
        "public": "Adulte",
        "format": "Roman journal",
        "structure": "Fragmentée",
        "cadre": {"lieu": "Ville contemporaine", "temps": "Présent"},
        "nombre_chapitres": 17,
        "caracteres_par_chapitre": 4412,
        "schema_principal": "SchemaNarratifFragmenté",
        "schema_complementaire": "SchemaNarratifCirculaire",
    },
    {
        "nom": "Érotique romantique pour New Adult",
        "genres": ["Roman sentimental", "Roman érotique"],
        "ton": "Lyrique",
        "public": "New adult",
        "format": "Roman journal",
        "structure": "Flashback",
        "cadre": {"lieu": "Ville contemporaine", "temps": "Présent"},
        "nombre_chapitres": 14,
        "caracteres_par_chapitre": 5357,
        "schema_principal": "SchemaNarratifFlashback",
        "schema_complementaire": "SchemaActanciel",
    },
    {
        "nom": "Conte absurde et initiatique",
        "genres": ["Roman initiatique", "Roman humoristique"],
        "ton": "Absurde",
        "public": "Adolescent",
        "format": "Roman classique",
        "structure": "Circulaire",
        "cadre": {"lieu": "Univers inventé", "temps": "Intemporel"},
        "nombre_chapitres": 9,
        "caracteres_par_chapitre": 8333,
        "schema_principal": "SchemaNarratifCirculaire",
        "schema_complementaire": "SchemaNarratifStructureAbsurde",
    },
    {
        "nom": "Solarpunk utopique",
        "genres": ["Roman de science-fiction"],
        "ton": "Lyrique",
        "public": "Jeune adulte (YA)",
        "format": "Roman graphique",
        "structure": "Linéaire",
        "cadre": {"lieu": "Futur urbain", "temps": "Futur"},
        "nombre_chapitres": 11,
        "caracteres_par_chapitre": 6818,
        "schema_principal": "SchemaNarratifClassique",
        "schema_complementaire": "VoyageDuHeros",
    },
    {
        "nom": "Polar épistolaire rural",
        "genres": ["Roman policier"],
        "ton": "Ironique",
        "public": "Adulte",
        "format": "Roman épistolaire",
        "structure": "Cadre",
        "cadre": {"lieu": "Campagne historique", "temps": "Passé"},
        "nombre_chapitres": 12,
        "caracteres_par_chapitre": 6250,
        "schema_principal": "SchemaNarratifEpistolaire",
        "schema_complementaire": "SchemaNarratifRomanPolicier",
    },
    {
        "nom": "Drame familial choral",
        "genres": ["Roman réaliste", "Roman psychologique"],
        "ton": "Dramatique",
        "public": "Adulte",
        "format": "Roman choral",
        "structure": "Flashback",
        "cadre": {"lieu": "Ville contemporaine", "temps": "Présent"},
        "nombre_chapitres": 16,
        "caracteres_par_chapitre": 4688,
        "schema_principal": "SchemaNarratifFlashback",
        "schema_complementaire": "SchemaNarratifFragmenté",
    }
]

def tirer_scenario():
    return random.choice(structure_romans)
