import random
structure_romans = [
    {
        "nom": "Romance historique épistolaire",
        "genres": ["Roman sentimental", "Roman historique"],
        "ton": "Lyrique",
        "public": "Adulte",
        "format": "Roman épistolaire",
        "structure": "Cadre",
        "cadre": {"lieu": "Campagne historique", "temps": "Passé"},
        "nombre_chapitres": 12,
        "caracteres_par_chapitre": 6250,
        "schema_principal": "Schéma cadre (récit enchâssé)",
        "schema_complementaire": "Schéma classique (5 étapes)",
        "exemple_œuvre": "Les Liaisons dangereuses"
    },
    {
        "nom": "Thriller psychologique contemporain",
        "genres": ["Roman policier", "Roman psychologique"],
        "ton": "Sombre",
        "public": "Adulte",
        "format": "Roman choral",
        "structure": "Fragmentée",
        "cadre": {"lieu": "Ville contemporaine", "temps": "Présent"},
        "nombre_chapitres": 15,
        "caracteres_par_chapitre": 5000,
        "schema_principal": "Schéma fragmenté (multi-POV)",
        "schema_complementaire": "Pyramide de Freytag",
        "exemple_œuvre": "Gone Girl"
    },
    {
        "nom": "Science-fantasy épique",
        "genres": ["Roman de fantasy", "Roman de science-fiction"],
        "ton": "Épique",
        "public": "Jeune adulte (YA)",
        "format": "Roman classique",
        "structure": "Linéaire",
        "cadre": {"lieu": "Univers inventé", "temps": "Intemporel"},
        "nombre_chapitres": 10,
        "caracteres_par_chapitre": 7500,
        "schema_principal": "Voyage du héros (Campbell)",
        "schema_complementaire": "Schéma actanciel (Greimas)",
        "exemple_œuvre": "Dune"
    },
    {
        "nom": "Uchronie philosophique",
        "genres": ["Roman historique", "Roman de science-fiction"],
        "ton": "Ironique",
        "public": "Adulte",
        "format": "Roman mosaïque",
        "structure": "In medias res",
        "cadre": {"lieu": "Ville contemporaine", "temps": "Futur"},
        "nombre_chapitres": 14,
        "caracteres_par_chapitre": 5357,
        "schema_principal": "In medias res",
        "schema_complementaire": "Schéma quinaire (Larivaille)",
        "exemple_œuvre": "Le Maître du Haut Château"
    },
    {
        "nom": "Romantasy lyrique pour jeunes adultes",
        "genres": ["Roman sentimental", "Roman de fantasy"],
        "ton": "Lyrique",
        "public": "Jeune adulte (YA)",
        "format": "Roman journal",
        "structure": "Flashback",
        "cadre": {"lieu": "Univers inventé", "temps": "Intemporel"},
        "nombre_chapitres": 15,
        "caracteres_par_chapitre": 5000,
        "schema_principal": "Flashback",
        "schema_complementaire": "Schéma actanciel",
        "exemple_œuvre": "La Sélection"
    },
    {
        "nom": "Chick lit humoristique",
        "genres": ["Roman humoristique", "Roman sentimental"],
        "ton": "Comique",
        "public": "Adulte",
        "format": "Roman classique",
        "structure": "Linéaire",
        "cadre": {"lieu": "Ville contemporaine", "temps": "Présent"},
        "nombre_chapitres": 12,
        "caracteres_par_chapitre": 6250,
        "schema_principal": "Schéma classique",
        "schema_complementaire": "Structure en 3 actes",
        "exemple_œuvre": "Le Journal de Bridget Jones"
    },
    {
        "nom": "Dystopie sociale post-apocalyptique",
        "genres": ["Roman dystopique", "Roman social"],
        "ton": "Tragique",
        "public": "Jeune adulte (YA)",
        "format": "Roman graphique",
        "structure": "Circulaire",
        "cadre": {"lieu": "Société post-apocalyptique", "temps": "Après une catastrophe"},
        "nombre_chapitres": 16,
        "caracteres_par_chapitre": 4688,
        "schema_principal": "Schéma circulaire",
        "schema_complementaire": "Pyramide de Freytag",
        "exemple_œuvre": "Hunger Games"
    },
    {
        "nom": "Fantastique gothique en huis clos",
        "genres": ["Roman fantastique", "Roman d'horreur"],
        "ton": "Sombre",
        "public": "Adulte",
        "format": "Roman classique",
        "structure": "Cadre",
        "cadre": {"lieu": "Lieu clos (huis clos)", "temps": "Passé"},
        "nombre_chapitres": 8,
        "caracteres_par_chapitre": 9375,
        "schema_principal": "Schéma cadre",
        "schema_complementaire": "Schéma classique horrifique",
        "exemple_œuvre": "Le Tour d'écrou"
    },
    {
        "nom": "Cyberpunk dramatique",
        "genres": ["Roman de science-fiction"],
        "ton": "Dramatique",
        "public": "Adulte",
        "format": "Roman choral",
        "structure": "Fragmentée",
        "cadre": {"lieu": "Futur urbain", "temps": "Futur"},
        "nombre_chapitres": 20,
        "caracteres_par_chapitre": 3750,
        "schema_principal": "Schéma fragmenté",
        "schema_complementaire": "Schéma quinaire",
        "exemple_œuvre": "Neuromancien"
    },
    {
        "nom": "Roman initiatique pour enfants",
        "genres": ["Roman initiatique"],
        "ton": "Comique",
        "public": "Enfant",
        "format": "Roman classique",
        "structure": "Linéaire",
        "cadre": {"lieu": "Ville contemporaine", "temps": "Présent"},
        "nombre_chapitres": 10,
        "caracteres_par_chapitre": 7500,
        "schema_principal": "Voyage du héros simplifié",
        "schema_complementaire": "Schéma classique",
        "exemple_œuvre": "Le Petit Prince"
    },
    {
        "nom": "Steampunk à suspense",
        "genres": ["Roman historique", "Roman de science-fiction"],
        "ton": "Dramatique",
        "public": "Adulte",
        "format": "Roman mosaïque",
        "structure": "In medias res",
        "cadre": {"lieu": "Ville industrielle", "temps": "Passé"},
        "nombre_chapitres": 13,
        "caracteres_par_chapitre": 5769,
        "schema_principal": "In medias res",
        "schema_complementaire": "Schéma actanciel",
        "exemple_œuvre": "L'Affaire Jack l'Éventreur"
    },
    {
        "nom": "Roman philosophique spatial",
        "genres": ["Roman philosophique", "Roman de science-fiction"],
        "ton": "Lyrique",
        "public": "Adulte",
        "format": "Roman journal",
        "structure": "Fragmentée",
        "cadre": {"lieu": "Espace intergalactique", "temps": "Futur lointain"},
        "nombre_chapitres": 18,
        "caracteres_par_chapitre": 4167,
        "schema_principal": "Schéma fragmenté",
        "schema_complementaire": "Schéma circulaire",
        "exemple_œuvre": "Solaris"
    },
    {
        "nom": "Roman noir social",
        "genres": ["Roman noir", "Roman social"],
        "ton": "Sombre",
        "public": "Adulte",
        "format": "Roman choral",
        "structure": "Flashback",
        "cadre": {"lieu": "Ville contemporaine", "temps": "Présent"},
        "nombre_chapitres": 15,
        "caracteres_par_chapitre": 5000,
        "schema_principal": "Flashback",
        "schema_complementaire": "Schéma dramatique",
        "exemple_œuvre": "L.A. Confidential"
    },
    {
        "nom": "Épopée fantasy initiatique",
        "genres": ["Roman de fantasy", "Roman initiatique"],
        "ton": "Épique",
        "public": "Jeune adulte (YA)",
        "format": "Roman classique",
        "structure": "Linéaire",
        "cadre": {"lieu": "Univers inventé", "temps": "Intemporel"},
        "nombre_chapitres": 12,
        "caracteres_par_chapitre": 6250,
        "schema_principal": "Voyage du héros",
        "schema_complementaire": "Schéma actanciel",
        "exemple_œuvre": "L'Assassin royal"
    },
    {
        "nom": "Autofiction existentielle",
        "genres": ["Roman autobiographique", "Roman philosophique"],
        "ton": "Lyrique",
        "public": "Adulte",
        "format": "Roman journal",
        "structure": "Fragmentée",
        "cadre": {"lieu": "Ville contemporaine", "temps": "Présent"},
        "nombre_chapitres": 17,
        "caracteres_par_chapitre": 4412,
        "schema_principal": "Schéma fragmenté",
        "schema_complementaire": "Schéma circulaire",
        "exemple_œuvre": "Les Mots"
    },
    {
        "nom": "Érotique romantique pour New Adult",
        "genres": ["Roman sentimental", "Roman érotique"],
        "ton": "Lyrique",
        "public": "New adult",
        "format": "Roman journal",
        "structure": "Flashback",
        "cadre": {"lieu": "Ville contemporaine", "temps": "Présent"},
        "nombre_chapitres": 14,
        "caracteres_par_chapitre": 5357,
        "schema_principal": "Flashback",
        "schema_complementaire": "Schéma actanciel",
        "exemple_œuvre": "Cinquante nuances de Grey"
    },
    {
        "nom": "Conte absurde et initiatique",
        "genres": ["Roman initiatique", "Roman humoristique"],
        "ton": "Absurde",
        "public": "Adolescent",
        "format": "Roman classique",
        "structure": "Circulaire",
        "cadre": {"lieu": "Univers inventé", "temps": "Intemporel"},
        "nombre_chapitres": 9,
        "caracteres_par_chapitre": 8333,
        "schema_principal": "Schéma circulaire",
        "schema_complementaire": "Structure absurde",
        "exemple_œuvre": "Alice au pays des merveilles"
    },
    {
        "nom": "Solarpunk utopique",
        "genres": ["Roman de science-fiction"],
        "ton": "Lyrique",
        "public": "Jeune adulte (YA)",
        "format": "Roman graphique",
        "structure": "Linéaire",
        "cadre": {"lieu": "Futur urbain", "temps": "Futur"},
        "nombre_chapitres": 11,
        "caracteres_par_chapitre": 6818,
        "schema_principal": "Schéma classique",
        "schema_complementaire": "Voyage du héros optimiste",
        "exemple_œuvre": "The Dispossessed"
    },
    {
        "nom": "Polar épistolaire rural",
        "genres": ["Roman policier"],
        "ton": "Ironique",
        "public": "Adulte",
        "format": "Roman épistolaire",
        "structure": "Cadre",
        "cadre": {"lieu": "Campagne historique", "temps": "Passé"},
        "nombre_chapitres": 12,
        "caracteres_par_chapitre": 6250,
        "schema_principal": "Schéma cadre épistolaire",
        "schema_complementaire": "Schéma classique policier",
        "exemple_œuvre": "Le Crime de l'Orient-Express"
    },
    {
        "nom": "Drame familial choral",
        "genres": ["Roman réaliste", "Roman psychologique"],
        "ton": "Dramatique",
        "public": "Adulte",
        "format": "Roman choral",
        "structure": "Flashback",
        "cadre": {"lieu": "Ville contemporaine", "temps": "Présent"},
        "nombre_chapitres": 16,
        "caracteres_par_chapitre": 4688,
        "schema_principal": "Flashback",
        "schema_complementaire": "Schéma fragmenté",
        "exemple_œuvre": "Petits meurtres entre amis"
    }
]

def tirer_scenario():
    return random.choice(structure_romans)
